export class Jugador{
  id: number= 0
  NombreJugador:string=""
  apellido:string=""
  username:string=""
  email:string=""
  direccion:string=""
  cuidad:string=""
  estado:string=""
  ApellidoJugador:string=""
  EdadJugador:string=""
  NacionalidadJugador:string=""
  AlturaJugador:string=""
  PosicionJugador:string=""
  ClubAnteriorJugador:string=""
  ClubActualJugador:string=""
  ValorMercadoJugador:string=""
  SalarioJugador:string=""
  PartidosJugadosJugador:string=""
  GolesJugador:string=""
  AsistenciasJugador:string=""
    }
